[[target]]
file = "/image/tiff/reader.go"
line = 72

[[target]]
file = "/image/tiff/reader.go"
line = 392

[[target]]
file = "/image/tiff/reader.go"
line = 484

[[target]]
file = "/image/tiff/reader.go"
line = 686
