[[target]]
file = "/image/png/reader.go"
line = 174

[[target]]
file = "/image/png/reader.go"
line = 610

[[target]]
file = "/image/png/reader.go"
line = 875

[[target]]
file = "/image/png/reader.go"
line = 936
