[[target]]
file = "/image/tiff/reader.go"
line = 71

[[target]]
file = "/image/tiff/reader.go"
line = 392

[[target]]
file = "/image/tiff/reader.go"
line = 482

[[target]]
file = "/image/tiff/reader.go"
line = 686
